// <auto-generated />
using System;
using LightInvest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightInvest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250316195205_population")]
    partial class population
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LightInvest.Models.DadosInstalacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConsumoPainel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Inclinacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ModeloPainelId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPaineis")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoInstalacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("ModeloPainelId");

                    b.ToTable("DadosInstalacao");
                });

            modelBuilder.Entity("LightInvest.Models.EnergyConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("ConsumoDiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ConsumoFimSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsumoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaFimSemana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaSemana")
                        .HasColumnType("decimal(18,2)");

                    b.PrimitiveCollection<string>("MesesOcupacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnergyConsumptions");
                });

            modelBuilder.Entity("LightInvest.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("LightInvest.Models.RoiCalculator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumoEnergeticoMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumoEnergeticoRede")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustoInstalacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustoManutencaoAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataCalculado")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ROI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RetornoEconomia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ROICalculators");
                });

            modelBuilder.Entity("LightInvest.Models.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nome")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("LightInvest.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LightInvest.Models.b.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Albufeira"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Almada"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Amadora"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Aveiro"
                        },
                        new
                        {
                            Id = 30,
                            Nome = "Barreiro"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Barcelos"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Beja"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Braga"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Bragança"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Caldas da Rainha"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Cascais"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Coimbra"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Évora"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Faro"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Figueira da Foz"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Funchal"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Guarda"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Guimarães"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Leiria"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Lisboa"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Matosinhos"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Montijo"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Odivelas"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Oeiras"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Portalegre"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "Portimão"
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Porto"
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Póvoa de Varzim"
                        },
                        new
                        {
                            Id = 28,
                            Nome = "Santarem"
                        },
                        new
                        {
                            Id = 29,
                            Nome = "Setúbal"
                        },
                        new
                        {
                            Id = 31,
                            Nome = "Sintra"
                        },
                        new
                        {
                            Id = 32,
                            Nome = "Tomar"
                        },
                        new
                        {
                            Id = 33,
                            Nome = "Torres Vedras"
                        },
                        new
                        {
                            Id = 34,
                            Nome = "Viana do castelo"
                        },
                        new
                        {
                            Id = 35,
                            Nome = "Vila do Conde"
                        },
                        new
                        {
                            Id = 36,
                            Nome = "Vila Nova de Gaia"
                        },
                        new
                        {
                            Id = 37,
                            Nome = "Viseu"
                        });
                });

            modelBuilder.Entity("LightInvest.Models.b.ModeloPainelSolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ModelosDePaineisSolares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Modelo = "Aiko - Comet 2U"
                        },
                        new
                        {
                            Id = 2,
                            Modelo = "Maxeon 7"
                        },
                        new
                        {
                            Id = 3,
                            Modelo = "Longi - HI-MO X6"
                        },
                        new
                        {
                            Id = 4,
                            Modelo = "Huasun - Himalaya"
                        },
                        new
                        {
                            Id = 5,
                            Modelo = "TW Solar"
                        },
                        new
                        {
                            Id = 6,
                            Modelo = "JA Solar DeepBlue 4.0 Pro"
                        },
                        new
                        {
                            Id = 7,
                            Modelo = "Astroenergy - Astro N5"
                        },
                        new
                        {
                            Id = 8,
                            Modelo = "Grand Sunergy"
                        },
                        new
                        {
                            Id = 9,
                            Modelo = "DMEGC - Infinity RT"
                        },
                        new
                        {
                            Id = 10,
                            Modelo = "Spic"
                        });
                });

            modelBuilder.Entity("LightInvest.Models.b.PotenciaPainelSolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PainelSolarId")
                        .HasColumnType("int");

                    b.Property<decimal>("Potencia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PainelSolarId");

                    b.ToTable("PotenciasDePaineisSolares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PainelSolarId = 1,
                            Potencia = 670m
                        },
                        new
                        {
                            Id = 2,
                            PainelSolarId = 2,
                            Potencia = 445m
                        },
                        new
                        {
                            Id = 3,
                            PainelSolarId = 3,
                            Potencia = 600m
                        },
                        new
                        {
                            Id = 4,
                            PainelSolarId = 4,
                            Potencia = 720m
                        },
                        new
                        {
                            Id = 5,
                            PainelSolarId = 5,
                            Potencia = 715m
                        },
                        new
                        {
                            Id = 6,
                            PainelSolarId = 5,
                            Potencia = 590m
                        },
                        new
                        {
                            Id = 7,
                            PainelSolarId = 6,
                            Potencia = 595m
                        },
                        new
                        {
                            Id = 8,
                            PainelSolarId = 7,
                            Potencia = 640m
                        },
                        new
                        {
                            Id = 9,
                            PainelSolarId = 8,
                            Potencia = 710m
                        },
                        new
                        {
                            Id = 10,
                            PainelSolarId = 9,
                            Potencia = 615m
                        },
                        new
                        {
                            Id = 11,
                            PainelSolarId = 10,
                            Potencia = 410m
                        });
                });

            modelBuilder.Entity("LightInvest.Models.DadosInstalacao", b =>
                {
                    b.HasOne("LightInvest.Models.b.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightInvest.Models.b.ModeloPainelSolar", "ModeloPainel")
                        .WithMany()
                        .HasForeignKey("ModeloPainelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("ModeloPainel");
                });

            modelBuilder.Entity("LightInvest.Models.b.PotenciaPainelSolar", b =>
                {
                    b.HasOne("LightInvest.Models.b.ModeloPainelSolar", "PainelSolar")
                        .WithMany("Potencias")
                        .HasForeignKey("PainelSolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PainelSolar");
                });

            modelBuilder.Entity("LightInvest.Models.b.ModeloPainelSolar", b =>
                {
                    b.Navigation("Potencias");
                });
#pragma warning restore 612, 618
        }
    }
}
