// <auto-generated />
using System;
using LightInvest.Models.BD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightInvest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250404115254_AddComentarioLikeTable4")]
    partial class AddComentarioLikeTable4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Artigo", b =>
                {
                    b.Property<int>("ArtigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtigoId"));

                    b.Property<int?>("ArtigoId1")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoCurta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ArtigoId");

                    b.HasIndex("ArtigoId1");

                    b.ToTable("Artigos");

                    b.HasData(
                        new
                        {
                            ArtigoId = 1,
                            Categoria = "Energia Renovável",
                            Conteudo = "\r\nA energia solar é uma fonte renovável e limpa que se está a tornar cada vez mais popular devido aos seus benefícios econômicos e ambientais. Este artigo explora as vantagens de adotar a energia solar tanto para residências quanto para empresas.\r\n\r\n### Benefícios Econômicos\r\n- **Redução de Custos:** A principal vantagem da energia solar é a redução da conta de energia elétrica. Ao gerar sua própria eletricidade, diminui a dependência da rede elétrica.\r\n- **Valorização do Imóvel:** Imóveis que possuem sistemas de energia solar são geralmente mais valorizados no mercado, uma vez que têm custos operacionais menores e atraem compradores interessados em soluções sustentáveis.\r\n- **Incentivos e Subsídios:** Em muitas regiões, o governo oferece incentivos fiscais e subsídios para a instalação de sistemas fotovoltaicos, tornando o investimento mais acessível.\r\n\r\n### Benefícios Ambientais\r\n- **Redução da Pegada de Carbono:** A energia solar não emite gases de efeito estufa, o que contribui significativamente para a redução da pegada de carbono.\r\n- **Fontes Renováveis:** Ao contrário das fontes de energia tradicionais, como o carvão e o gás natural, a energia solar é renovável e não esgota os recursos naturais do planeta.\r\n\r\n### Conclusão\r\nInvestir em sistemas de energia solar é uma escolha inteligente tanto do ponto de vista econômico quanto ambiental. Ao reduzir os custos com eletricidade e contribuir para a preservação do meio ambiente, a energia solar torna-se uma solução cada vez mais viável e atraente.",
                            DataPublicacao = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCurta = "Entenda os benefícios da energia solar para a sua residência ou empresa.",
                            ImagemUrl = "~/images/energia-solar.jpg",
                            Titulo = "Benefícios da Energia Solar"
                        },
                        new
                        {
                            ArtigoId = 2,
                            Categoria = "ROI",
                            Conteudo = "\r\nCalcular o Retorno sobre o Investimento (ROI) em sistemas fotovoltaicos é essencial para avaliar a viabilidade financeira de um projeto. Este artigo explica como calcular o ROI e por que ele é importante para qualquer instalação de energia solar.\r\n\r\n### O que é o ROI?\r\nO ROI é uma métrica financeira usada para avaliar o desempenho de um investimento. Ele calcula o lucro ou perda relativa ao valor investido e é expresso como uma porcentagem.\r\n\r\n### Fórmula do ROI\r\nA fórmula básica para calcular o ROI é a seguinte:\r\nPara um sistema de energia solar, o retorno pode incluir a economia na conta de energia elétrica, o valor dos incentivos fiscais, e a possível valorização do imóvel. O custo do investimento inclui a instalação dos painéis solares, manutenção e outros custos operacionais. Se tiver interesse nesta máteria na nossa plataforma consegues aceder à ferramenta do cálculo do ROI.\r\n\r\n### Exemplo de Cálculo do ROI\r\nSuponhamos que investiu ´20.000 € numm sistema de energia solar e, ao longo do tempo, economizou 3.000 € anualmente na sua conta de energia elétrica. O cálculo do ROI seria: ROI (%) = (Retorno do Investimento / Custo do Investimento) x 100\r\n\r\n\r\nIsso significa que, em média, terá um retorno de 15% do valor investido a cada ano.\r\n\r\n### Conclusão\r\nO cálculo do ROI ajuda a determinar se o investimento em energia solar vale a pena. Com os dados certos, consegue analisar e avaliar a viabilidade financeira e o tempo de retorno do seu investimento em energia solar.",
                            DataPublicacao = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCurta = "Aprenda a calcular o ROI de um sistema fotovoltaico e entenda se o investimento vale a pena.",
                            ImagemUrl = "/images/artigos/calcular-roi.jpg",
                            Titulo = "Como Calcular o Retorno sobre o Investimento em Energia Solar"
                        },
                        new
                        {
                            ArtigoId = 3,
                            Categoria = "Painéis Solares",
                            Conteudo = "\r\nPlanear e instalar um sistema de energia solar requer um processo detalhado e bem coordenado. Este artigo apresenta um guia completo sobre como planear e executar a instalação de um sistema fotovoltaico de forma eficiente.\r\n\r\n### Passos para o Planeamento\r\n1. **Análise de Viabilidade:** Antes de iniciar, é importante realizar uma análise detalhada do local, levando em consideração fatores como o consumo de energia, a localização e a inclinação do telhado.\r\n2. **Dimensionamento do Sistema:** A quantidade de energia que um sistema solar pode gerar depende do número de painéis e da capacidade de cada um. O dimensionamento correto do sistema é crucial para maximizar a eficiência.\r\n3. **Escolha dos Componentes:** Os componentes principais de um sistema solar são os painéis solares, o inversor e a estrutura de montagem. Escolher materiais de boa qualidade é essencial para garantir o bom funcionamento e a longevidade do sistema.\r\n\r\n### Processo de Instalação\r\n- **Instalação dos Painéis Solares:** Os painéis solares devem ser instalados de forma a otimizar a exposição solar, garantindo que eles recebam a maior quantidade de luz possível ao longo do dia.\r\n- **Conexão Elétrica:** A instalação elétrica envolve a ligação dos painéis solares ao inversor, que converte a energia gerada em energia utilizável para a residência ou empresa.\r\n- **Testes e Comissionamento:** Após a instalação, é necessário realizar testes para garantir que o sistema está funcionando corretamente e de forma segura.\r\n\r\n### Conclusão\r\nA instalação de sistemas solares é um processo técnico que exige um planeamento cuidadoso. Um bom planeamento e a escolha de profissionais qualificados podem garantir que o sistema solar seja eficiente e tenha uma vida útil longa.",
                            DataPublicacao = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCurta = "Dicas essenciais para planear e instalar um sistema de energia solar de forma eficiente.",
                            ImagemUrl = "/images/artigos/planeamento-solar.jpg",
                            Titulo = "Planeamento e Instalação de Sistemas de Energia Solar"
                        });
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtigoId")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoId");

                    b.HasIndex("UserId");

                    b.ToTable("Comentario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtigoId = 1,
                            Autor = "Rodrigo",
                            DataCriacao = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Ótimo artigo! Muito informativo.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArtigoId = 1,
                            Autor = "Rodrigo",
                            DataCriacao = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Gostei bastante das explicações sobre os benefícios ambientais!",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ArtigoId = 2,
                            Autor = "Rodrigo",
                            DataCriacao = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "A ferramenta de cálculo do ROI seria muito útil! Vocês têm alguma recomendação?",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.ComentarioLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComentarioId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("UserId");

                    b.ToTable("ComentarioLike");
                });

            modelBuilder.Entity("LightInvest.Models.Ener.DadosInstalacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<int>("Dificuldade")
                        .HasColumnType("int");

                    b.Property<decimal>("Inclinacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ModeloPainelId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPaineis")
                        .HasColumnType("int");

                    b.Property<int>("PotenciaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoInstalacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("ModeloPainelId");

                    b.HasIndex("PotenciaId");

                    b.ToTable("DadosInstalacao");
                });

            modelBuilder.Entity("LightInvest.Models.Roi.RoiCalculator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumoEnergeticoMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumoEnergeticoRede")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustoInstalacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustoManutencaoAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataCalculado")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ROI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RetornoEconomia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ROICalculators");
                });

            modelBuilder.Entity("LightInvest.Models.Simulacao.Energ.EnergyConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsumoDiaSemana")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsumoFimSemana")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsumoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaFimSemana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaSemana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MesesOcupacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnergyConsumptions");
                });

            modelBuilder.Entity("LightInvest.Models.Simulacao.Tarifa.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecoKWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("LightInvest.Models.Utilizador.Login.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "rodrigo.elias2003@gmail.com",
                            IsAdmin = true,
                            Name = "Rodrigo",
                            Password = "rodrigoR123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "veragfernandes04@gmail.com",
                            IsAdmin = true,
                            Name = "Vera",
                            Password = "Vera1234"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ligthinvestuser@gmail.com",
                            IsAdmin = false,
                            Name = "LightInvest ",
                            Password = "LightInvest123"
                        });
                });

            modelBuilder.Entity("LightInvest.Models.Utilizador.Pass.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("LightInvest.Models.b.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Albufeira"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Almada"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Amadora"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Aveiro"
                        },
                        new
                        {
                            Id = 30,
                            Nome = "Barreiro"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Barcelos"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Beja"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Braga"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Bragança"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Caldas da Rainha"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Cascais"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Coimbra"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Évora"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Faro"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Figueira da Foz"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Funchal"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Guarda"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Guimarães"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Leiria"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Lisboa"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Matosinhos"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Montijo"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Odivelas"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Oeiras"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Portalegre"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "Portimão"
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Porto"
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Póvoa de Varzim"
                        },
                        new
                        {
                            Id = 28,
                            Nome = "Santarem"
                        },
                        new
                        {
                            Id = 29,
                            Nome = "Setúbal"
                        },
                        new
                        {
                            Id = 31,
                            Nome = "Sintra"
                        },
                        new
                        {
                            Id = 32,
                            Nome = "Tomar"
                        },
                        new
                        {
                            Id = 33,
                            Nome = "Torres Vedras"
                        },
                        new
                        {
                            Id = 34,
                            Nome = "Viana do castelo"
                        },
                        new
                        {
                            Id = 35,
                            Nome = "Vila do Conde"
                        },
                        new
                        {
                            Id = 36,
                            Nome = "Vila Nova de Gaia"
                        },
                        new
                        {
                            Id = 37,
                            Nome = "Viseu"
                        });
                });

            modelBuilder.Entity("LightInvest.Models.b.ModeloPainelSolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ModeloNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ModelosDePaineisSolares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModeloNome = "Aiko - Comet 2U",
                            Preco = 1250.00m
                        },
                        new
                        {
                            Id = 2,
                            ModeloNome = "Maxeon 7",
                            Preco = 1320.00m
                        },
                        new
                        {
                            Id = 3,
                            ModeloNome = "Longi - HI-MO X6",
                            Preco = 1280.00m
                        },
                        new
                        {
                            Id = 4,
                            ModeloNome = "Huasun - Himalaya",
                            Preco = 1300.00m
                        },
                        new
                        {
                            Id = 5,
                            ModeloNome = "TW Solar",
                            Preco = 1230.00m
                        },
                        new
                        {
                            Id = 6,
                            ModeloNome = "JA Solar DeepBlue 4.0 Pro",
                            Preco = 1270.00m
                        },
                        new
                        {
                            Id = 7,
                            ModeloNome = "Astroenergy - Astro N5",
                            Preco = 1260.00m
                        },
                        new
                        {
                            Id = 8,
                            ModeloNome = "Grand Sunergy",
                            Preco = 1240.00m
                        },
                        new
                        {
                            Id = 9,
                            ModeloNome = "DMEGC - Infinity RT",
                            Preco = 1290.00m
                        },
                        new
                        {
                            Id = 10,
                            ModeloNome = "Spic",
                            Preco = 910.00m
                        });
                });

            modelBuilder.Entity("LightInvest.Models.b.PotenciaPainelSolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModeloPainelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Potencia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ModeloPainelId");

                    b.ToTable("PotenciasDePaineisSolares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModeloPainelId = 1,
                            Potencia = 670m
                        },
                        new
                        {
                            Id = 2,
                            ModeloPainelId = 1,
                            Potencia = 680m
                        },
                        new
                        {
                            Id = 3,
                            ModeloPainelId = 1,
                            Potencia = 690m
                        },
                        new
                        {
                            Id = 4,
                            ModeloPainelId = 1,
                            Potencia = 700m
                        },
                        new
                        {
                            Id = 5,
                            ModeloPainelId = 2,
                            Potencia = 445m
                        },
                        new
                        {
                            Id = 6,
                            ModeloPainelId = 2,
                            Potencia = 455m
                        },
                        new
                        {
                            Id = 7,
                            ModeloPainelId = 2,
                            Potencia = 465m
                        },
                        new
                        {
                            Id = 8,
                            ModeloPainelId = 2,
                            Potencia = 475m
                        },
                        new
                        {
                            Id = 9,
                            ModeloPainelId = 3,
                            Potencia = 600m
                        },
                        new
                        {
                            Id = 10,
                            ModeloPainelId = 3,
                            Potencia = 610m
                        },
                        new
                        {
                            Id = 11,
                            ModeloPainelId = 3,
                            Potencia = 620m
                        },
                        new
                        {
                            Id = 12,
                            ModeloPainelId = 3,
                            Potencia = 630m
                        },
                        new
                        {
                            Id = 13,
                            ModeloPainelId = 4,
                            Potencia = 720m
                        },
                        new
                        {
                            Id = 14,
                            ModeloPainelId = 4,
                            Potencia = 730m
                        },
                        new
                        {
                            Id = 15,
                            ModeloPainelId = 4,
                            Potencia = 740m
                        },
                        new
                        {
                            Id = 16,
                            ModeloPainelId = 4,
                            Potencia = 750m
                        },
                        new
                        {
                            Id = 17,
                            ModeloPainelId = 5,
                            Potencia = 715m
                        },
                        new
                        {
                            Id = 18,
                            ModeloPainelId = 5,
                            Potencia = 725m
                        },
                        new
                        {
                            Id = 19,
                            ModeloPainelId = 5,
                            Potencia = 735m
                        },
                        new
                        {
                            Id = 20,
                            ModeloPainelId = 5,
                            Potencia = 745m
                        },
                        new
                        {
                            Id = 21,
                            ModeloPainelId = 5,
                            Potencia = 590m
                        },
                        new
                        {
                            Id = 22,
                            ModeloPainelId = 5,
                            Potencia = 600m
                        },
                        new
                        {
                            Id = 23,
                            ModeloPainelId = 5,
                            Potencia = 610m
                        },
                        new
                        {
                            Id = 24,
                            ModeloPainelId = 5,
                            Potencia = 620m
                        },
                        new
                        {
                            Id = 25,
                            ModeloPainelId = 6,
                            Potencia = 595m
                        },
                        new
                        {
                            Id = 26,
                            ModeloPainelId = 6,
                            Potencia = 605m
                        },
                        new
                        {
                            Id = 27,
                            ModeloPainelId = 6,
                            Potencia = 615m
                        },
                        new
                        {
                            Id = 28,
                            ModeloPainelId = 6,
                            Potencia = 625m
                        },
                        new
                        {
                            Id = 29,
                            ModeloPainelId = 7,
                            Potencia = 640m
                        },
                        new
                        {
                            Id = 30,
                            ModeloPainelId = 7,
                            Potencia = 650m
                        },
                        new
                        {
                            Id = 31,
                            ModeloPainelId = 7,
                            Potencia = 660m
                        },
                        new
                        {
                            Id = 32,
                            ModeloPainelId = 7,
                            Potencia = 670m
                        },
                        new
                        {
                            Id = 33,
                            ModeloPainelId = 8,
                            Potencia = 710m
                        },
                        new
                        {
                            Id = 34,
                            ModeloPainelId = 8,
                            Potencia = 720m
                        },
                        new
                        {
                            Id = 35,
                            ModeloPainelId = 8,
                            Potencia = 730m
                        },
                        new
                        {
                            Id = 36,
                            ModeloPainelId = 8,
                            Potencia = 740m
                        },
                        new
                        {
                            Id = 37,
                            ModeloPainelId = 9,
                            Potencia = 615m
                        },
                        new
                        {
                            Id = 38,
                            ModeloPainelId = 9,
                            Potencia = 625m
                        },
                        new
                        {
                            Id = 39,
                            ModeloPainelId = 9,
                            Potencia = 635m
                        },
                        new
                        {
                            Id = 40,
                            ModeloPainelId = 9,
                            Potencia = 645m
                        },
                        new
                        {
                            Id = 41,
                            ModeloPainelId = 10,
                            Potencia = 410m
                        },
                        new
                        {
                            Id = 42,
                            ModeloPainelId = 10,
                            Potencia = 420m
                        },
                        new
                        {
                            Id = 43,
                            ModeloPainelId = 10,
                            Potencia = 430m
                        },
                        new
                        {
                            Id = 44,
                            ModeloPainelId = 10,
                            Potencia = 440m
                        });
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Artigo", b =>
                {
                    b.HasOne("LightInvest.Models.Educ.Artigos.Artigo", null)
                        .WithMany("ArtigosRelacionados")
                        .HasForeignKey("ArtigoId1");
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Comentario", b =>
                {
                    b.HasOne("LightInvest.Models.Educ.Artigos.Artigo", "Artigo")
                        .WithMany("Comentarios")
                        .HasForeignKey("ArtigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightInvest.Models.Utilizador.Login.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Artigo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.ComentarioLike", b =>
                {
                    b.HasOne("LightInvest.Models.Educ.Artigos.Comentario", "Comentario")
                        .WithMany("Likes")
                        .HasForeignKey("ComentarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightInvest.Models.Utilizador.Login.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comentario");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LightInvest.Models.Ener.DadosInstalacao", b =>
                {
                    b.HasOne("LightInvest.Models.b.Cidade", "Cidade")
                        .WithMany("DadosInstalacoes")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightInvest.Models.b.ModeloPainelSolar", "ModeloPainel")
                        .WithMany()
                        .HasForeignKey("ModeloPainelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightInvest.Models.b.PotenciaPainelSolar", "Potencia")
                        .WithMany()
                        .HasForeignKey("PotenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("ModeloPainel");

                    b.Navigation("Potencia");
                });

            modelBuilder.Entity("LightInvest.Models.b.PotenciaPainelSolar", b =>
                {
                    b.HasOne("LightInvest.Models.b.ModeloPainelSolar", "ModeloPainelSolar")
                        .WithMany("Potencias")
                        .HasForeignKey("ModeloPainelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModeloPainelSolar");
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Artigo", b =>
                {
                    b.Navigation("ArtigosRelacionados");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Comentario", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("LightInvest.Models.b.Cidade", b =>
                {
                    b.Navigation("DadosInstalacoes");
                });

            modelBuilder.Entity("LightInvest.Models.b.ModeloPainelSolar", b =>
                {
                    b.Navigation("Potencias");
                });
#pragma warning restore 612, 618
        }
    }
}
