// <auto-generated />
using System;
using LightInvest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightInvest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250315035324_CreateDadosInstalacaoTable")]
    partial class CreateDadosInstalacaoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LightInvest.Models.DadosInstalacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConsumoPainel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Inclinacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ModeloPainelId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPaineis")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("ModeloPainelId");

                    b.ToTable("DadosInstalacao");
                });

            modelBuilder.Entity("LightInvest.Models.EnergyConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("ConsumoDiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ConsumoFimSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsumoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaFimSemana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaSemana")
                        .HasColumnType("decimal(18,2)");

                    b.PrimitiveCollection<string>("MesesOcupacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnergyConsumptions");
                });

            modelBuilder.Entity("LightInvest.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("LightInvest.Models.RoiCalculator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumoEnergeticoMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumoEnergeticoRede")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustoInstalacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustoManutencaoAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataCalculado")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ROI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RetornoEconomia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ROICalculators");
                });

            modelBuilder.Entity("LightInvest.Models.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nome")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("LightInvest.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LightInvest.Models.b.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Lisboa"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Porto"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Coimbra"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Funchal"
                        });
                });

            modelBuilder.Entity("LightInvest.Models.b.ModeloPainelSolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ModelosDePaineisSolares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Modelo = "Modelo A"
                        },
                        new
                        {
                            Id = 2,
                            Modelo = "Modelo B"
                        },
                        new
                        {
                            Id = 3,
                            Modelo = "Modelo C"
                        });
                });

            modelBuilder.Entity("LightInvest.Models.b.PotenciaPainelSolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PainelSolarId")
                        .HasColumnType("int");

                    b.Property<decimal>("Potencia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PainelSolarId");

                    b.ToTable("PotenciasDePaineisSolares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PainelSolarId = 1,
                            Potencia = 250m
                        },
                        new
                        {
                            Id = 2,
                            PainelSolarId = 2,
                            Potencia = 300m
                        },
                        new
                        {
                            Id = 3,
                            PainelSolarId = 3,
                            Potencia = 350m
                        });
                });

            modelBuilder.Entity("LightInvest.Models.DadosInstalacao", b =>
                {
                    b.HasOne("LightInvest.Models.b.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightInvest.Models.b.ModeloPainelSolar", "ModeloPainel")
                        .WithMany()
                        .HasForeignKey("ModeloPainelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("ModeloPainel");
                });

            modelBuilder.Entity("LightInvest.Models.b.PotenciaPainelSolar", b =>
                {
                    b.HasOne("LightInvest.Models.b.ModeloPainelSolar", "PainelSolar")
                        .WithMany("Potencias")
                        .HasForeignKey("PainelSolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PainelSolar");
                });

            modelBuilder.Entity("LightInvest.Models.b.ModeloPainelSolar", b =>
                {
                    b.Navigation("Potencias");
                });
#pragma warning restore 612, 618
        }
    }
}
