// <auto-generated />
using System;
using LightInvest.Models.BD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightInvest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Artigo", b =>
                {
                    b.Property<int>("ArtigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtigoId"));

                    b.Property<int?>("ArtigoId1")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoCurta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ArtigoId");

                    b.HasIndex("ArtigoId1");

                    b.ToTable("Artigos");

                    b.HasData(
                        new
                        {
                            ArtigoId = 1,
                            Categoria = "Energia Renovável",
                            Conteudo = "\r\nA energia solar é uma fonte renovável e limpa que se está a tornar cada vez mais popular devido aos seus benefícios econômicos e ambientais. Este artigo explora as vantagens de adotar a energia solar tanto para residências quanto para empresas.\r\n\r\n### Benefícios Econômicos\r\n- **Redução de Custos:** A principal vantagem da energia solar é a redução da conta de energia elétrica. Ao gerar sua própria eletricidade, diminui a dependência da rede elétrica.\r\n- **Valorização do Imóvel:** Imóveis que possuem sistemas de energia solar são geralmente mais valorizados no mercado, uma vez que têm custos operacionais menores e atraem compradores interessados em soluções sustentáveis.\r\n- **Incentivos e Subsídios:** Em muitas regiões, o governo oferece incentivos fiscais e subsídios para a instalação de sistemas fotovoltaicos, tornando o investimento mais acessível.\r\n\r\n### Benefícios Ambientais\r\n- **Redução da Pegada de Carbono:** A energia solar não emite gases de efeito estufa, o que contribui significativamente para a redução da pegada de carbono.\r\n- **Fontes Renováveis:** Ao contrário das fontes de energia tradicionais, como o carvão e o gás natural, a energia solar é renovável e não esgota os recursos naturais do planeta.\r\n\r\n### Conclusão\r\nInvestir em sistemas de energia solar é uma escolha inteligente tanto do ponto de vista econômico quanto ambiental. Ao reduzir os custos com eletricidade e contribuir para a preservação do meio ambiente, a energia solar torna-se uma solução cada vez mais viável e atraente.",
                            DataPublicacao = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCurta = "Entenda os benefícios da energia solar para a sua residência ou empresa.",
                            ImagemUrl = "~/images/energia-solar.jpg",
                            Titulo = "Benefícios da Energia Solar"
                        },
                        new
                        {
                            ArtigoId = 2,
                            Categoria = "ROI",
                            Conteudo = "\r\nCalcular o Retorno sobre o Investimento (ROI) em sistemas fotovoltaicos é essencial para avaliar a viabilidade financeira de um projeto. Este artigo explica como calcular o ROI e por que ele é importante para qualquer instalação de energia solar.\r\n\r\n### O que é o ROI?\r\nO ROI é uma métrica financeira usada para avaliar o desempenho de um investimento. Ele calcula o lucro ou perda relativa ao valor investido e é expresso como uma porcentagem.\r\n\r\n### Fórmula do ROI\r\nA fórmula básica para calcular o ROI é a seguinte:\r\nPara um sistema de energia solar, o retorno pode incluir a economia na conta de energia elétrica, o valor dos incentivos fiscais, e a possível valorização do imóvel. O custo do investimento inclui a instalação dos painéis solares, manutenção e outros custos operacionais. Se tiver interesse nesta máteria na nossa plataforma consegues aceder à ferramenta do cálculo do ROI.\r\n\r\n### Exemplo de Cálculo do ROI\r\nSuponhamos que investiu ´20.000 € numm sistema de energia solar e, ao longo do tempo, economizou 3.000 € anualmente na sua conta de energia elétrica. O cálculo do ROI seria: ROI (%) = (Retorno do Investimento / Custo do Investimento) x 100\r\n\r\n\r\nIsso significa que, em média, terá um retorno de 15% do valor investido a cada ano.\r\n\r\n### Conclusão\r\nO cálculo do ROI ajuda a determinar se o investimento em energia solar vale a pena. Com os dados certos, consegue analisar e avaliar a viabilidade financeira e o tempo de retorno do seu investimento em energia solar.",
                            DataPublicacao = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCurta = "Aprenda a calcular o ROI de um sistema fotovoltaico e entenda se o investimento vale a pena.",
                            ImagemUrl = "/images/artigos/calcular-roi.jpg",
                            Titulo = "Como Calcular o Retorno sobre o Investimento em Energia Solar"
                        },
                        new
                        {
                            ArtigoId = 3,
                            Categoria = "Painéis Solares",
                            Conteudo = "\r\nPlanear e instalar um sistema de energia solar requer um processo detalhado e bem coordenado. Este artigo apresenta um guia completo sobre como planear e executar a instalação de um sistema fotovoltaico de forma eficiente.\r\n\r\n### Passos para o Planeamento\r\n1. **Análise de Viabilidade:** Antes de iniciar, é importante realizar uma análise detalhada do local, levando em consideração fatores como o consumo de energia, a localização e a inclinação do telhado.\r\n2. **Dimensionamento do Sistema:** A quantidade de energia que um sistema solar pode gerar depende do número de painéis e da capacidade de cada um. O dimensionamento correto do sistema é crucial para maximizar a eficiência.\r\n3. **Escolha dos Componentes:** Os componentes principais de um sistema solar são os painéis solares, o inversor e a estrutura de montagem. Escolher materiais de boa qualidade é essencial para garantir o bom funcionamento e a longevidade do sistema.\r\n\r\n### Processo de Instalação\r\n- **Instalação dos Painéis Solares:** Os painéis solares devem ser instalados de forma a otimizar a exposição solar, garantindo que eles recebam a maior quantidade de luz possível ao longo do dia.\r\n- **Conexão Elétrica:** A instalação elétrica envolve a ligação dos painéis solares ao inversor, que converte a energia gerada em energia utilizável para a residência ou empresa.\r\n- **Testes e Comissionamento:** Após a instalação, é necessário realizar testes para garantir que o sistema está funcionando corretamente e de forma segura.\r\n\r\n### Conclusão\r\nA instalação de sistemas solares é um processo técnico que exige um planeamento cuidadoso. Um bom planeamento e a escolha de profissionais qualificados podem garantir que o sistema solar seja eficiente e tenha uma vida útil longa.",
                            DataPublicacao = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCurta = "Dicas essenciais para planear e instalar um sistema de energia solar de forma eficiente.",
                            ImagemUrl = "/images/artigos/planeamento-solar.jpg",
                            Titulo = "Planeamento e Instalação de Sistemas de Energia Solar"
                        },
                        new
                        {
                            ArtigoId = 4,
                            Categoria = "Energia Renovável",
                            Conteudo = "\r\nA eficiência energética é uma das estratégias mais eficazes para reduzir a fatura de eletricidade. Este artigo apresenta algumas práticas simples e acessíveis que podem fazer a diferença no consumo de energia.\r\n\r\n### Dicas de Eficiência Energética\r\n1. **Iluminação LED:** Trocar lâmpadas incandescentes por LEDs pode reduzir significativamente o consumo de energia em casa ou na empresa.\r\n2. **Equipamentos Eficientes:** Optar por eletrodomésticos com classificação energética A+++ garante menor consumo de energia.\r\n3. **Isolamento Térmico:** Melhorar o isolamento térmico das divisões reduz o uso excessivo de aquecedores e ar-condicionado.\r\n\r\n### Benefícios\r\n- Redução imediata na fatura mensal;\r\n- Menor impacto ambiental;\r\n- Valorização do imóvel.\r\n\r\n### Conclusão\r\nInvestir em eficiência energética é uma solução sustentável que permite poupar dinheiro e proteger o meio ambiente.",
                            DataPublicacao = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCurta = "Descobre como poupar energia e reduzir custos com medidas simples e eficientes.",
                            ImagemUrl = "/images/artigos/eficiencia-energetica.jpg",
                            Titulo = "Como Reduzir a Fatura de Energia com Eficiência Energética"
                        },
                        new
                        {
                            ArtigoId = 5,
                            Categoria = "Energia Renovável",
                            Conteudo = "\r\nPortugal tem-se destacado como um dos países europeus com maior aposta em energias renováveis. Conhece as principais vantagens de investir nesta área.\r\n\r\n### Benefícios das Renováveis\r\n1. **Redução de Custos:** A longo prazo, os investimentos em energia solar ou eólica geram poupanças consideráveis na fatura de energia.\r\n2. **Sustentabilidade Ambiental:** Reduzem a pegada de carbono e protegem os recursos naturais.\r\n3. **Incentivos e Apoios:** Existem vários programas e incentivos estatais para quem pretende investir em energias renováveis.\r\n\r\n### Perspetivas Futuras\r\nPortugal continuará a expandir a sua produção de energia limpa, criando oportunidades de investimento e desenvolvimento tecnológico.\r\n\r\n### Conclusão\r\nInvestir em energias renováveis em Portugal é uma decisão inteligente, com benefícios económicos e ambientais a curto e longo prazo.",
                            DataPublicacao = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCurta = "Conhece as principais vantagens de apostar nas energias renováveis em Portugal.",
                            ImagemUrl = "/images/artigos/renovaveis-portugal.jpg",
                            Titulo = "Vantagens de Investir em Energia Renovável em Portugal"
                        },
                        new
                        {
                            ArtigoId = 6,
                            Categoria = "Painéis Solares",
                            Conteudo = "\r\nA manutenção preventiva dos painéis solares é fundamental para garantir o seu correto funcionamento e prolongar a sua vida útil. Neste artigo, partilhamos boas práticas essenciais.\r\n\r\n### Cuidados a Ter\r\n1. **Limpeza Regular:** A acumulação de poeira, folhas ou resíduos nos painéis pode reduzir a eficiência da produção de energia.\r\n2. **Inspeção de Cablagens:** Verificar se os cabos e conexões estão em bom estado evita perdas de energia ou avarias.\r\n3. **Monitorização de Desempenho:** Utilizar sistemas de monitorização permite detetar rapidamente qualquer anomalia.\r\n\r\n### Benefícios da Manutenção\r\n- Aumento da eficiência energética;\r\n- Prevenção de danos graves;\r\n- Maior rentabilidade do investimento.\r\n\r\n### Conclusão\r\nA manutenção preventiva dos painéis solares é um passo simples, mas essencial, para garantir o melhor desempenho do sistema a longo prazo.",
                            DataPublicacao = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCurta = "Aprende boas práticas para manter os painéis solares sempre eficientes e seguros.",
                            ImagemUrl = "/images/artigos/manutencao-paineis.jpg",
                            Titulo = "Manutenção Preventiva de Painéis Solares: Boas Práticas"
                        });
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtigoId")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoId");

                    b.HasIndex("UserId");

                    b.ToTable("Comentario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtigoId = 1,
                            Autor = "Rodrigo",
                            DataCriacao = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Ótimo artigo! Muito informativo.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArtigoId = 1,
                            Autor = "Rodrigo",
                            DataCriacao = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Gostei bastante das explicações sobre os benefícios ambientais!",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ArtigoId = 2,
                            Autor = "Rodrigo",
                            DataCriacao = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "A ferramenta de cálculo do ROI seria muito útil! Vocês têm alguma recomendação?",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            ArtigoId = 1,
                            Autor = "Tiago Silva",
                            DataCriacao = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Artigo muito esclarecedor, obrigado pela partilha!",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            ArtigoId = 1,
                            Autor = "Ana Costa",
                            DataCriacao = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Gostava de ver mais exemplos práticos.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            ArtigoId = 1,
                            Autor = "João Ferreira",
                            DataCriacao = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Concordo plenamente com o que foi escrito.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            ArtigoId = 1,
                            Autor = "Marta Santos",
                            DataCriacao = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Já sigo o vosso site há algum tempo, excelente trabalho.",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            ArtigoId = 2,
                            Autor = "Bruno Rocha",
                            DataCriacao = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Também tenho dúvidas em relação ao ROI, podiam fazer um artigo só sobre isso.",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            ArtigoId = 2,
                            Autor = "Carla Mendes",
                            DataCriacao = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Muito bom conteúdo, continue assim!",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            ArtigoId = 2,
                            Autor = "Diogo Gomes",
                            DataCriacao = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Conseguem partilhar fontes adicionais sobre este tema?",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            ArtigoId = 2,
                            Autor = "Filipa Ribeiro",
                            DataCriacao = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Gostei muito deste artigo, bem explicado.",
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            ArtigoId = 2,
                            Autor = "André Sousa",
                            DataCriacao = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Tenho uma sugestão de tema: fundos de investimento.",
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            ArtigoId = 3,
                            Autor = "Raquel Almeida",
                            DataCriacao = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Excelente conteúdo, parabéns!",
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            ArtigoId = 3,
                            Autor = "Pedro Martins",
                            DataCriacao = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Muito completo e detalhado.",
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            ArtigoId = 3,
                            Autor = "Sofia Lopes",
                            DataCriacao = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Era bom ter uma versão em vídeo também.",
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            ArtigoId = 3,
                            Autor = "Ricardo Pinto",
                            DataCriacao = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Óptima explicação dos conceitos base.",
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            ArtigoId = 3,
                            Autor = "Patrícia Nunes",
                            DataCriacao = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "A parte dos exemplos ajudou-me muito.",
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            ArtigoId = 1,
                            Autor = "Luís Carvalho",
                            DataCriacao = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Gostava de saber mais sobre análise técnica.",
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            ArtigoId = 1,
                            Autor = "Beatriz Fonseca",
                            DataCriacao = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Parabéns pelo artigo, muito bem escrito.",
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            ArtigoId = 1,
                            Autor = "Miguel Teixeira",
                            DataCriacao = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "O conteúdo foi muito útil para mim, obrigado.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            ArtigoId = 2,
                            Autor = "Cátia Barros",
                            DataCriacao = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Seria interessante aprofundar sobre ETFs.",
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            ArtigoId = 2,
                            Autor = "Hugo Correia",
                            DataCriacao = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Já partilhei com amigos, muito bom!",
                            UserId = 22
                        },
                        new
                        {
                            Id = 23,
                            ArtigoId = 2,
                            Autor = "Daniela Faria",
                            DataCriacao = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Ajudou-me a perceber melhor o mercado.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 24,
                            ArtigoId = 5,
                            Autor = "Tiago Silva",
                            DataCriacao = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Este artigo me ajudou a entender melhor a importância da análise de mercado. Parabéns!",
                            UserId = 4
                        },
                        new
                        {
                            Id = 25,
                            ArtigoId = 5,
                            Autor = "Ana Costa",
                            DataCriacao = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Muito interessante, mas eu gostaria de mais exemplos de ferramentas.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 26,
                            ArtigoId = 5,
                            Autor = "João Ferreira",
                            DataCriacao = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Acho que poderiam adicionar mais estudos de caso sobre ROI. Isso ajudaria bastante.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 27,
                            ArtigoId = 5,
                            Autor = "Marta Santos",
                            DataCriacao = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Adorei a forma como o conteúdo foi estruturado. Fácil de entender!",
                            UserId = 7
                        },
                        new
                        {
                            Id = 28,
                            ArtigoId = 6,
                            Autor = "Bruno Rocha",
                            DataCriacao = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Muito bom, já compartilhei com a minha rede de contatos. Espero ver mais artigos assim.",
                            UserId = 8
                        },
                        new
                        {
                            Id = 29,
                            ArtigoId = 6,
                            Autor = "Carla Mendes",
                            DataCriacao = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Preciso de mais informações sobre como aplicar isso em investimentos pessoais.",
                            UserId = 9
                        },
                        new
                        {
                            Id = 30,
                            ArtigoId = 6,
                            Autor = "Diogo Gomes",
                            DataCriacao = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Texto = "Muito relevante para quem está iniciando no mercado financeiro. Obrigado pelo conteúdo.",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.ComentarioLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComentarioId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("UserId");

                    b.ToTable("ComentarioLike");
                });

            modelBuilder.Entity("LightInvest.Models.Ener.DadosInstalacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<int>("Dificuldade")
                        .HasColumnType("int");

                    b.Property<decimal>("Inclinacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ModeloPainelId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPaineis")
                        .HasColumnType("int");

                    b.Property<int>("PotenciaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoInstalacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("ModeloPainelId");

                    b.HasIndex("PotenciaId");

                    b.ToTable("DadosInstalacao");
                });

            modelBuilder.Entity("LightInvest.Models.Roi.RoiCalculator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumoEnergeticoMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumoEnergeticoRede")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustoInstalacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustoManutencaoAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataCalculado")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ROI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RetornoEconomia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ROICalculators");
                });

            modelBuilder.Entity("LightInvest.Models.Simulacao.Energ.EnergyConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsumoDiaSemana")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsumoFimSemana")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsumoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaFimSemana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediaSemana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MesesOcupacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnergyConsumptions");
                });

            modelBuilder.Entity("LightInvest.Models.Simulacao.Tarifa.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecoKWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("LightInvest.Models.Utilizador.Login.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "lightinvestsup2425@gmail.com",
                            IsAdmin = true,
                            Name = "LighInvestSupport",
                            Password = "LightInvestSup123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ligthinvestuser@gmail.com",
                            IsAdmin = false,
                            Name = "LightInvest",
                            Password = "LightInvest123"
                        },
                        new
                        {
                            Id = 24,
                            Email = "rodrigo.elias2003@gmail.com",
                            IsAdmin = true,
                            Name = "Rodrigo Elias",
                            Password = "rodrigoR123"
                        },
                        new
                        {
                            Id = 25,
                            Email = "veragfernandes04@gmail.com",
                            IsAdmin = true,
                            Name = "Vera Fernandes",
                            Password = "veraF123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "tiagosilva@gmail.com",
                            IsAdmin = false,
                            Name = "Tiago Silva",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "anacosta@hotmail.com",
                            IsAdmin = false,
                            Name = "Ana Costa",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 6,
                            Email = "joaoferreira@sapo.pt",
                            IsAdmin = false,
                            Name = "João Ferreira",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 7,
                            Email = "martasantos@gmail.com",
                            IsAdmin = false,
                            Name = "Marta Santos",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 8,
                            Email = "brunorocha@hotmail.com",
                            IsAdmin = false,
                            Name = "Bruno Rocha",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 9,
                            Email = "carlamendes@sapo.pt",
                            IsAdmin = false,
                            Name = "Carla Mendes",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 10,
                            Email = "diogogomes@gmail.com",
                            IsAdmin = false,
                            Name = "Diogo Gomes",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 11,
                            Email = "filiparibeiro@hotmail.com",
                            IsAdmin = false,
                            Name = "Filipa Ribeiro",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 12,
                            Email = "andresousa@sapo.pt",
                            IsAdmin = false,
                            Name = "André Sousa",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 13,
                            Email = "raquelalmeida@gmail.com",
                            IsAdmin = false,
                            Name = "Raquel Almeida",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 14,
                            Email = "pedromartins@hotmail.com",
                            IsAdmin = false,
                            Name = "Pedro Martins",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 15,
                            Email = "sofialopes@sapo.pt",
                            IsAdmin = false,
                            Name = "Sofia Lopes",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 16,
                            Email = "ricardopinto@gmail.com",
                            IsAdmin = false,
                            Name = "Ricardo Pinto",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 17,
                            Email = "patricianunes@hotmail.com",
                            IsAdmin = false,
                            Name = "Patrícia Nunes",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 18,
                            Email = "luiscarvalho@sapo.pt",
                            IsAdmin = false,
                            Name = "Luís Carvalho",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 19,
                            Email = "beatrizfonseca@gmail.com",
                            IsAdmin = false,
                            Name = "Beatriz Fonseca",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 20,
                            Email = "miguelteixeira@hotmail.com",
                            IsAdmin = false,
                            Name = "Miguel Teixeira",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 21,
                            Email = "catiabarros@sapo.pt",
                            IsAdmin = false,
                            Name = "Cátia Barros",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 22,
                            Email = "hugocorreia@gmail.com",
                            IsAdmin = false,
                            Name = "Hugo Correia",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 23,
                            Email = "danielafaria@hotmail.com",
                            IsAdmin = false,
                            Name = "Daniela Faria",
                            Password = "Password123"
                        });
                });

            modelBuilder.Entity("LightInvest.Models.Utilizador.Pass.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("LightInvest.Models.b.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Albufeira"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Almada"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Amadora"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Aveiro"
                        },
                        new
                        {
                            Id = 30,
                            Nome = "Barreiro"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Barcelos"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Beja"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Braga"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Bragança"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Caldas da Rainha"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Cascais"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Coimbra"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Évora"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Faro"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Figueira da Foz"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Funchal"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Guarda"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Guimarães"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Leiria"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Lisboa"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Matosinhos"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Montijo"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Odivelas"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Oeiras"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Portalegre"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "Portimão"
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Porto"
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Póvoa de Varzim"
                        },
                        new
                        {
                            Id = 28,
                            Nome = "Santarem"
                        },
                        new
                        {
                            Id = 29,
                            Nome = "Setúbal"
                        },
                        new
                        {
                            Id = 31,
                            Nome = "Sintra"
                        },
                        new
                        {
                            Id = 32,
                            Nome = "Tomar"
                        },
                        new
                        {
                            Id = 33,
                            Nome = "Torres Vedras"
                        },
                        new
                        {
                            Id = 34,
                            Nome = "Viana do castelo"
                        },
                        new
                        {
                            Id = 35,
                            Nome = "Vila do Conde"
                        },
                        new
                        {
                            Id = 36,
                            Nome = "Vila Nova de Gaia"
                        },
                        new
                        {
                            Id = 37,
                            Nome = "Viseu"
                        });
                });

            modelBuilder.Entity("LightInvest.Models.b.ModeloPainelSolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ModeloNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ModelosDePaineisSolares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModeloNome = "Aiko - Comet 2U",
                            Preco = 1250.00m
                        },
                        new
                        {
                            Id = 2,
                            ModeloNome = "Maxeon 7",
                            Preco = 1320.00m
                        },
                        new
                        {
                            Id = 3,
                            ModeloNome = "Longi - HI-MO X6",
                            Preco = 1280.00m
                        },
                        new
                        {
                            Id = 4,
                            ModeloNome = "Huasun - Himalaya",
                            Preco = 1300.00m
                        },
                        new
                        {
                            Id = 5,
                            ModeloNome = "TW Solar",
                            Preco = 1230.00m
                        },
                        new
                        {
                            Id = 6,
                            ModeloNome = "JA Solar DeepBlue 4.0 Pro",
                            Preco = 1270.00m
                        },
                        new
                        {
                            Id = 7,
                            ModeloNome = "Astroenergy - Astro N5",
                            Preco = 1260.00m
                        },
                        new
                        {
                            Id = 8,
                            ModeloNome = "Grand Sunergy",
                            Preco = 1240.00m
                        },
                        new
                        {
                            Id = 9,
                            ModeloNome = "DMEGC - Infinity RT",
                            Preco = 1290.00m
                        },
                        new
                        {
                            Id = 10,
                            ModeloNome = "Spic",
                            Preco = 910.00m
                        });
                });

            modelBuilder.Entity("LightInvest.Models.b.PotenciaPainelSolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModeloPainelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Potencia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ModeloPainelId");

                    b.ToTable("PotenciasDePaineisSolares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModeloPainelId = 1,
                            Potencia = 670m
                        },
                        new
                        {
                            Id = 2,
                            ModeloPainelId = 1,
                            Potencia = 680m
                        },
                        new
                        {
                            Id = 3,
                            ModeloPainelId = 1,
                            Potencia = 690m
                        },
                        new
                        {
                            Id = 4,
                            ModeloPainelId = 1,
                            Potencia = 700m
                        },
                        new
                        {
                            Id = 5,
                            ModeloPainelId = 2,
                            Potencia = 445m
                        },
                        new
                        {
                            Id = 6,
                            ModeloPainelId = 2,
                            Potencia = 455m
                        },
                        new
                        {
                            Id = 7,
                            ModeloPainelId = 2,
                            Potencia = 465m
                        },
                        new
                        {
                            Id = 8,
                            ModeloPainelId = 2,
                            Potencia = 475m
                        },
                        new
                        {
                            Id = 9,
                            ModeloPainelId = 3,
                            Potencia = 600m
                        },
                        new
                        {
                            Id = 10,
                            ModeloPainelId = 3,
                            Potencia = 610m
                        },
                        new
                        {
                            Id = 11,
                            ModeloPainelId = 3,
                            Potencia = 620m
                        },
                        new
                        {
                            Id = 12,
                            ModeloPainelId = 3,
                            Potencia = 630m
                        },
                        new
                        {
                            Id = 13,
                            ModeloPainelId = 4,
                            Potencia = 720m
                        },
                        new
                        {
                            Id = 14,
                            ModeloPainelId = 4,
                            Potencia = 730m
                        },
                        new
                        {
                            Id = 15,
                            ModeloPainelId = 4,
                            Potencia = 740m
                        },
                        new
                        {
                            Id = 16,
                            ModeloPainelId = 4,
                            Potencia = 750m
                        },
                        new
                        {
                            Id = 17,
                            ModeloPainelId = 5,
                            Potencia = 715m
                        },
                        new
                        {
                            Id = 18,
                            ModeloPainelId = 5,
                            Potencia = 725m
                        },
                        new
                        {
                            Id = 19,
                            ModeloPainelId = 5,
                            Potencia = 735m
                        },
                        new
                        {
                            Id = 20,
                            ModeloPainelId = 5,
                            Potencia = 745m
                        },
                        new
                        {
                            Id = 21,
                            ModeloPainelId = 5,
                            Potencia = 590m
                        },
                        new
                        {
                            Id = 22,
                            ModeloPainelId = 5,
                            Potencia = 600m
                        },
                        new
                        {
                            Id = 23,
                            ModeloPainelId = 5,
                            Potencia = 610m
                        },
                        new
                        {
                            Id = 24,
                            ModeloPainelId = 5,
                            Potencia = 620m
                        },
                        new
                        {
                            Id = 25,
                            ModeloPainelId = 6,
                            Potencia = 595m
                        },
                        new
                        {
                            Id = 26,
                            ModeloPainelId = 6,
                            Potencia = 605m
                        },
                        new
                        {
                            Id = 27,
                            ModeloPainelId = 6,
                            Potencia = 615m
                        },
                        new
                        {
                            Id = 28,
                            ModeloPainelId = 6,
                            Potencia = 625m
                        },
                        new
                        {
                            Id = 29,
                            ModeloPainelId = 7,
                            Potencia = 640m
                        },
                        new
                        {
                            Id = 30,
                            ModeloPainelId = 7,
                            Potencia = 650m
                        },
                        new
                        {
                            Id = 31,
                            ModeloPainelId = 7,
                            Potencia = 660m
                        },
                        new
                        {
                            Id = 32,
                            ModeloPainelId = 7,
                            Potencia = 670m
                        },
                        new
                        {
                            Id = 33,
                            ModeloPainelId = 8,
                            Potencia = 710m
                        },
                        new
                        {
                            Id = 34,
                            ModeloPainelId = 8,
                            Potencia = 720m
                        },
                        new
                        {
                            Id = 35,
                            ModeloPainelId = 8,
                            Potencia = 730m
                        },
                        new
                        {
                            Id = 36,
                            ModeloPainelId = 8,
                            Potencia = 740m
                        },
                        new
                        {
                            Id = 37,
                            ModeloPainelId = 9,
                            Potencia = 615m
                        },
                        new
                        {
                            Id = 38,
                            ModeloPainelId = 9,
                            Potencia = 625m
                        },
                        new
                        {
                            Id = 39,
                            ModeloPainelId = 9,
                            Potencia = 635m
                        },
                        new
                        {
                            Id = 40,
                            ModeloPainelId = 9,
                            Potencia = 645m
                        },
                        new
                        {
                            Id = 41,
                            ModeloPainelId = 10,
                            Potencia = 410m
                        },
                        new
                        {
                            Id = 42,
                            ModeloPainelId = 10,
                            Potencia = 420m
                        },
                        new
                        {
                            Id = 43,
                            ModeloPainelId = 10,
                            Potencia = 430m
                        },
                        new
                        {
                            Id = 44,
                            ModeloPainelId = 10,
                            Potencia = 440m
                        });
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Artigo", b =>
                {
                    b.HasOne("LightInvest.Models.Educ.Artigos.Artigo", null)
                        .WithMany("ArtigosRelacionados")
                        .HasForeignKey("ArtigoId1");
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Comentario", b =>
                {
                    b.HasOne("LightInvest.Models.Educ.Artigos.Artigo", "Artigo")
                        .WithMany("Comentarios")
                        .HasForeignKey("ArtigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightInvest.Models.Utilizador.Login.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Artigo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.ComentarioLike", b =>
                {
                    b.HasOne("LightInvest.Models.Educ.Artigos.Comentario", "Comentario")
                        .WithMany("Likes")
                        .HasForeignKey("ComentarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightInvest.Models.Utilizador.Login.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comentario");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LightInvest.Models.Ener.DadosInstalacao", b =>
                {
                    b.HasOne("LightInvest.Models.b.Cidade", "Cidade")
                        .WithMany("DadosInstalacoes")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightInvest.Models.b.ModeloPainelSolar", "ModeloPainel")
                        .WithMany()
                        .HasForeignKey("ModeloPainelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightInvest.Models.b.PotenciaPainelSolar", "Potencia")
                        .WithMany()
                        .HasForeignKey("PotenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("ModeloPainel");

                    b.Navigation("Potencia");
                });

            modelBuilder.Entity("LightInvest.Models.b.PotenciaPainelSolar", b =>
                {
                    b.HasOne("LightInvest.Models.b.ModeloPainelSolar", "ModeloPainelSolar")
                        .WithMany("Potencias")
                        .HasForeignKey("ModeloPainelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModeloPainelSolar");
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Artigo", b =>
                {
                    b.Navigation("ArtigosRelacionados");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("LightInvest.Models.Educ.Artigos.Comentario", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("LightInvest.Models.b.Cidade", b =>
                {
                    b.Navigation("DadosInstalacoes");
                });

            modelBuilder.Entity("LightInvest.Models.b.ModeloPainelSolar", b =>
                {
                    b.Navigation("Potencias");
                });
#pragma warning restore 612, 618
        }
    }
}
