name: .NET CI/CD

on:
  push:
    branches: [ "Main-new" ]
  pull_request:
    branches: [ "Main-new" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Cache NuGet packages
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore LightInvest/LightInvest.csproj

    # Install xmllint (caso necessário)
    - name: Install xmllint
      run: sudo apt-get install -y libxml2-utils


    # Build the project
    - name: Build
      run: dotnet build LightInvest/LightInvest.csproj --no-restore

    # Run tests
    - name: Test
      run: dotnet test LightInvest/LightInvest.csproj --no-build --verbosity normal

    # Publish (optional)
    - name: Publish
      run: dotnet publish LightInvest/LightInvest.csproj --configuration Release --output ./publish
