name: .NET CI/CD

on:
  push:
    branches: [ "Main-new" ]
  pull_request:
    branches: [ "Main-new" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Cache NuGet packages
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore LightInvest/LightInvest.csproj

    # Build the project
    - name: Build
      run: dotnet build LightInvest/LightInvest.csproj --no-restore

    # Run tests
    - name: Test
      run: dotnet test LightInvest/LightInvest.csproj --no-build --verbosity normal

    # Install Mono
    - name: Install Mono
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete

    # Run DocFX with Mono
    - name: Run DocFX
      run: mono /home/runner/.nuget/packages/docfx.console/2.59.4/tools/docfx.exe /home/runner/work/LightInvest/LightInvest/LightInvest/docfx.json -o output_directory -l log.txt --logLevel Warning
