name: .NET CI/CD

on:
  push:
    branches: [ "Main-new" ]
  pull_request:
    branches: [ "Main-new" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Cache NuGet packages
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore LightInvest/LightInvest.csproj

    # Build the project
    - name: Build the project
      run: dotnet build LightInvest/LightInvest.csproj --no-restore

    # Run tests
    - name: Run tests
      run: dotnet test LightInvest/LightInvest.csproj --no-build --verbosity normal

    # Install DocFX
    - name: Install DocFX
      run: dotnet tool install -g docfx

    # Generate documentation with DocFX, ignoring errors
    - name: Generate documentation with DocFX
      run: docfx build LightInvest/docfx.json --output LightInvest/_site --logLevel Warning
      continue-on-error: true  # Este passo ignora o erro caso ocorra
